#!/bin/bash

####################################################
########                                    ########
######         GnuPG nautilus scripts         ######
######                                        ######
######  ------------------------------------  ######
######                                        ######
######            License: GPLv3              ######
######      Algedi project: algedi@tin.it     ######
######                                        ######
######  ------------------------------------  ######
######                                        ######
######        KK   KK  UU      UU  II         ######
######        KK  KK   UU      UU  II         ######
######        KK KK    UU      UU  II         ######
######        KKKK     UU      UU  II         ######
######        KK KK    UU      UU  II         ######
######        KK  KK    UU    UU   II         ######
######        KK   KK     UUUU     II         ######
######                                        ######
####################################################

############################################################################

# GPGns 0.2 - GPG script nautilus
# Copyright (C) 2012 - algedi@tin.it - KUI team

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

############################################################################

cd "$NAUTILUS_SCRIPT_CURRENT_URI"
echo "1- gpg --list-key"
sListKey=$(gpg --list-key | grep "pub ")
sKeyElement=""
nField=1
for x in $sListKey
do
	if [ $x == "pub" ]; then
		nField=1
	fi
	if [ $nField == 2 ]; then
		sKeyElement="$sKeyElement ${x#*/}"
		sKeyDesc=$(gpg --list-key ${x#*/} | grep 'uid ' \
					| sed '2,$ d' | tr --squeeze-repeats ' ' \
					| sed 's/uid //' | sed 's/ /_/g')
		sKeyElement="$sKeyElement $sKeyDesc"
	fi	 
	nField=$(expr $nField + 1)
done

sKeySelected=$(zenity --list --height=300 --width=600 \
			--title="Elenco delle chiavi publiche disponibili" \
			--column="ID" --column="chiave" \
			${sKeyElement} \
			"Esci")

if [ "$sKeySelected" != "Esci" ]; then
	if [ "$sKeySelected" != "" ]; then
		for sFile in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
		do
 			gpg -e -a -r "$sKeySelected" "$sFile"
		done
	fi
fi 

